# Generated by Django 4.2.5 on 2023-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appAdmin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('adminNumber', models.CharField(max_length=5)),
                ('adminName', models.CharField(max_length=255)),
                ('adminPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
