# Generated by Django 4.2.5 on 2023-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecturer',
            fields=[
                ('lecturerID', models.AutoField(primary_key=True, serialize=False)),
                ('lecturerNumber', models.CharField(max_length=5)),
                ('lecturerName', models.CharField(max_length=255)),
                ('lecturerEmail', models.EmailField(max_length=255)),
                ('lecturerPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
