# Generated by Django 4.2.5 on 2023-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=255)),
                ('studentNumber', models.CharField(max_length=10, unique=True)),
                ('studentEmail', models.EmailField(max_length=254, unique=True)),
                ('studentFace', models.ImageField(upload_to='student_faces/')),
                ('modules', models.ManyToManyField(to='modules.module')),
            ],
        ),
    ]
